### ISSUE TITLE
maven-release-plugin configuration might need updating

### ISSUE THREAD

**Issue by mattnworb** [spotify/missinglink#57]
when I ran `mvn -B release:clean release:prepare release:perform` to release 0.1.4, it created a tag of `missinglink-parent-0.1.4` and the commit message was

>     [maven-release-plugin] prepare release missinglink-parent-0.1.4

https://github.com/spotify/missinglink/commit/8e7949304f408c195dbe26d9781c3f50e5625ebd

I had to create a tag `v0.1.4` manually

**Comment by caesar-ralf** [comment]
This is fixed after updating folsom-parent to the latest
